# Generated by Django 6.0.6 on 2026-07-05 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('email_domain', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organization_type', models.CharField(choices=[('club', 'Club'), ('society', 'Society'), ('department', 'Department'), ('office', 'Office'), ('group', 'Group')], max_length=20)),
                ('organization_class', models.CharField(choices=[('student', 'Student'), ('administrative', 'Administrative')], max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('tech', 'Tech'), ('sports', 'Sports'), ('arts', 'Arts'), ('business', 'Business'), ('religous', 'Religious'), ('other', 'Other')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='organization_covers/')),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.university')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_creator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='accounts.userpublic')),
            ],
            options={
                'db_table': 'organization_members',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership'), models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'member'])), name='Valid_role_check'), models.CheckConstraint(condition=models.Q(models.Q(('is_creator', True), _negated=True), ('role', 'admin'), _connector='OR'), name='creator_must_be_admin')],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_organization_name_per_university'),
        ),
    ]
