# Generated by Django 6.0.6 on 2026-07-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublic',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_profiles', to='organizations.university'),
        ),
        migrations.AddField(
            model_name='userpublic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userpublic',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_public_profile'),
        ),
    ]
